package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 8, 2013 5:48:40 AM PDT
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public interface DynSequence extends DynSequenceOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynSequence
