package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 8, 2013 5:48:37 AM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
	 * The value representing LIFESPAN_POLICY_ID.
	 */
  public static final int value = (int)(17L);
}
