package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, October 8, 2013 5:48:39 AM PDT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
   */
  public static final short value = (short)(1);
}
